#!bash

## restic environment variables
#RESTIC_PASSWORD_FILE=/etc/resticbackup.d/password
#RESTIC_REPOSITORY=/backup/restic

## resticbackup environment variables
#RESTICBACKUP_EXCLUDE_FILE=/etc/resticbackup.d/exclude
#RESTICBACKUP_LOG_FILE=-
## whether to check that the repository is a mount point
#RESTICBACKUP_MOUNTED=1
## arguments to pass to `restic forget` when pruning
#RESTICBACKUP_PRUNE_ARGS="--prune --keep-hourly 12 --keep-daily 7 --keep-weekly 4 --keep-monthly 3"

# check_mk hook options
#
# paths to check_mk spool files
#CHECKMK_INTEGRITY_SPOOL=/var/lib/check_mk_agent/spool/$((8*24*60*60))_check_restic_integrity
#CHECKMK_SNAPSHOTS_SPOOL=/var/lib/check_mk_agent/spool/$((3*24*60*60))_check_restic_snapshots
# thresholds for check_snaps hook, formatted like period:warn:crit
#CHECKMK_SNAPSHOTS_THRESHOLDS=1day:10:6

